version: "3"
services:
  postgres:
    image: "postgres:9.6"
    environment:
      POSTGRES_USER: odk
      POSTGRES_PASSWORD: odk
      POSTGRES_DATABASE: odk
  web:
    build: .
    ports:
      - "80:8383"
    volumes:
      - ".:/srv/odk"
    depends_on:
      - postgres
    command: [ "./wait-for-it.sh", "postgres:5432", "--", "./start-odk.sh" ]

